### ISSUE TITLE
Fix location footer yml socials

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1734]
Make them consistent with the footer.yml keys, for example:

```
socials:
  - name: "Facebook"
    icon: ""
    link: "https://www.facebook.com/4geeksacademyes"
```
