### ISSUE TITLE
Add property location to why_4geeks.lang.yml

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1926]
Currently the why_4geeks.lang.yml files contain a list of testimonials like this:

```yml
why:
  - title: "Consigue trabajo"
    description: "Únete a cientos de personas graduadas trabajando en compañías tecnológicas top: Construcción de perfil, Marca personal, Simulacros de entrevistas, etc."
    image: ../../../../static/images/why3.jpg
    alt: ""
    video: "https://www.youtube.com/watch?v=ln3bQsV1BaQ" # VIDEO URL --- LEAVE EMPTY "" IF YOU HAVEN'T THE VIDEO URL
    # video: "ln3bQsV1BaQ"
    icon: address
  - title: "Financiamos tu carrera"
    description: "No pagues nada desde el día uno hasta conseguir trabajo como programador con Income Share Agreement (ISA)."
    image: "../../../../static/images/why2.jpg"
    alt: ""
    video: "https://www.youtube.com/watch?v=MBXqEnhodx0" # VIDEO URL --- LEAVE EMPTY "" IF YOU HAVEN'T THE VIDEO URL
    # video: "MBXqEnhodx0"
    icon: handmoney
```

We should add a new `location` property to each of the items, then, we need to use that property to prioritize how thos testimonials are rendered, only the first 3 will render, and they need to be sort by location starting with the session.location on the website or landing page.

### Example implementation:

The news component already works like this, you can [read the YML](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/components/news/news.es.yaml) or the pages/landings in which is being used to understand how to replicate that behavior here.
