### ISSUE TITLE
Website - Cintillo de Mensajes Varios

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1968]
En algunos momentos la web necesita proporcionar un cintillo de mensajes que se muestre en la parte superior, por encima del menu. 

La idea es que este mensaje sea customizable para cada sede y solo aparezca cuando haya un mensaje que mostrar, de lo contrario estará oculto, tal como se ve la web actual si él.}

El diseño está en el archivo Website Project de Figma en la page de IU Kit, 

Diseño propuesto
![banner1](https://user-images.githubusercontent.com/80764131/143300632-210610ce-e1e0-4eb4-9557-84f97b1b9d9e.jpg)

Ejemplo con todo el Menu
![Ejemplo](https://user-images.githubusercontent.com/80764131/143300669-cea88ed7-fbf2-41d1-9e52-4252198423e5.jpg)

**Comment by alesanchezr** [comment]
Lets call this component `CustomBar` and it will be always at the top, these are the confi properties:

```
active: boolean
message: HTML text (use _dangerouseHTML because we want the user to be able to customize anchors)
button: 
     label: "Read More"
     path: string (can be inline path using #, relative path or absolute path)
```
