### ISSUE TITLE
Add `link` property into each partner yml that allows to specify the URL to which the user will be taken if it clicks on the location logo

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2344]
https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/components/partner/partner.us.yaml

```
  images:
    - name: "Microsoft"
      link: https://microsoft.com
      #locations: ["miami-downtown"]
      #courses: ["machine-learning"]
      image: "../../../../static/images/partner/microsoft.png"
      featured: true
    - name: "Microsoft"
      link: "#top"
      #locations: ["miami-downtown"]
      #courses: ["machine-learning"]
      image: "../../../../static/images/partner/microsoft.png"
      featured: true
```
