### ISSUE TITLE
Fill Cluster YMLs with information needed to SEO optimize

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3865]
Dentro de ./src/data/cluster estaran puros archivos YML que se utilizaran para definir la informacion adicional de un cluster. Por ejemplo: ./src/data/cluster/trends-and-tech.us.yml

```
meta_info:
  slug: trends-and-tech
  title: "Aplica a 4Geeks Academy Bootcamp"
  visibility: "visible" # visible (default), hidden (not indexed) or unlisted (listed but not in sitemap).
  description: "Aplica a uno de los mejores bootcamps de código del mundo, online o en una de nuestras sedes: Miami, Santiago de Chile, Madrid, Costa Rica, Maracaibo y Caracas"
  image: "https://4geeks-academy-main.s3-us-west-2.amazonaws.com/PresentacionBienvenidaEstudiante1.jpg"
  keywords: "Aplica a 4Geeks Academy Bootcamp"
  redirects: ["/aplica", "/es/apply"]

seo_title: "Trends and Technology"
header:
    title: Próximos programas y Eventos de 4GEEKS ACADEMY
    paragraph: "Ajusta los filtros a los eventos de los cursos que más te interesan"
    image: ""
    image_alt: ""
```
![4Geeks-Academy-Miami-Coding-Bootcamp-Madrid-España-Santiago-de-Chile-and-Caracas-·-4Geeks-Academy (1)](https://user-images.githubusercontent.com/426452/207891689-4d422ce5-1e34-47ce-8038-384ec021adf9.png)
