### ISSUE TITLE
Llenar carouse el partners de la pagina web

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4014]
En este YML hemos colocado una seccion llamada: `partners_carousel`.
Esta sección es una lista de patrners que deseamos mostrar a otros potenciales partners de 4Geeks.
https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/components/partner/partner.es.yaml#L259
Nota: recuerdar llenar la version en ingles tambien.

Debemos pedirle a los country managers que nos pasen la informacion de sus 4 mejores y mas famosos partners, especificamente la siguiente info:

```yml
    - fist_name: "Jane"
      last_name: "Doe"
      sub_header: "CEO @ Globant"
      alt: "4Geeks Academy Partner"
      image: "../../../../static/images/students/student1.jpg"
      paragraph: |
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie massa et iaculis elementum. Aliquam pellentesque tincidunt dolor.,"
      linkedin: "https://www.linkedin.com"
```

Asi es como se ve:
<img width="1439" alt="Screen Shot 2023-01-05 at 9 09 38 PM" src="https://user-images.githubusercontent.com/426452/210915511-74fe21e8-d605-4e73-8ea3-32afdc036663.png">
