### ISSUE TITLE
Modificar el componente JobGuaranteeSmall para que solo se muestre en algunos campus

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#5154]
Necesitamos que JobGuaranteeSmall que está en todos los landings de campus no se muestre en los campus de Europa. Usamos hide_from_locations para especificar donde no queremos que aparezca

```
title: Job guarantee commitment
hide_from_locations: ["downtown-miami"]
icons:
  - icon: "graduation-2"
    title: Get a job within 180 days after graduation or get your money back.
  - icon: "network"
    title: Complete the stages of our career support procces.
  - icon: "network"
    title: Access a network of 5K hiring partners.
  - icon: "handshake"
    title: We both commit to your future career
```
