### ISSUE TITLE
Changes to the FaqCard component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5179]
# About how its being used:

Based on [this code](https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/location.js#L379): 

```jsx
 <FaqCard item={faqs} i={2} />
```

I'm proposing the following changes:

```jsx
 <FaqCard item={faqs} topicSlug={"4geeks"} locationSlug={"miami-downtown"} minPriority={2} />
```

- [ ] Property `i` has to be renamed to topicSlug, each topic in the FaqCard YML must have a unique slug.
- [ ] Each question can have a "location" array property that specifies if the question must be filtered and only show to a particular location, if empty it will be shown to all locations.
- [ ] Every time you use the `<FaqCard>` by default it should be used with the locationSlug from the session like this: `<FaqCard locationSlug={session.location} ...>` but the only exception is in the location page that it should be hardcoded to the location to which the landing page corresponds: `<FaqCard locationSlug={yml.breathecode_location_slug} ...>`
- [ ] Add a `priority` property to each question, a number from 0 to 5 that represents how important is the question, when using the component you can specific a `minPriority` that will essentially hide all the questions with lower priority than the minimum. 
- [ ] This `minPriority` index will be hardcoded on the javascript page, for example on the location it will be `maxPriorit=0` (only the most important ones).

```yml
  - topic: "Frequently Asked Questions about 4Geeks"
    slug: "4geeks"
    questions:
      - question: "Why 4Geeks Academy?"
        locations: ["santiago-chile"]
        priority: 0,
        answer: |-
          "Well, it's kind of weird to talk about yourself a lot ... but, okay, since you asked!
          We offer a unique methodology in which we will improve your general capabilities; We will train you and turn you into a software developer. We are constantly bringing innovative new approaches to teaching programming that not many other educational organizations are doing.
          "Breathe Coding". That's our motto, because we understand that to become a developer, you have to be part of the programming culture. We've made learning fun and we've mastered the art of showing how programming skills can fit into everyday life."
      - question: "Is 4Geeks a certified institution?"
        locations: ["miami-downtown"]
        priority: 1,
        answer: "For sure! We are licensed (not accredited) in Florida by the Commission for Independent Education of the Florida Department of Education"
      - question: "Why our campus?"
        locations: []
        priority: 1,
        answer: |-
          "Anywhere you choose to attend is an excellent option, whether it is in Miami, Madrid, Santiago de Chile, Caracas o San José in Costa Rica, in every city you will live an excellent experience with an environment totally prepared to offer you a unique learning experience through your journey."
      - question: "Who is that face in the logo?"
        locations: []
        priority: 3,
        answer: |-
          "Oh, you mean Rigoberto? He is the heart and spirit of everyone working for the Academy"
```
